[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 12
y = 12

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 700
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"
